name: Build PullRequest

on:
  push:
  workflow_call:
    inputs:
      triggered_by_comment:
        type: boolean
        required: false

jobs:
  main:
    name: Create ota commit
    runs-on: ubuntu-latest
    steps:
      - name: Print triggered_by_comment
        run: |
          if [ "${{ github.event_name }}" = "workflow_call" ]; then
            echo "triggered_by_comment: ${{ inputs.triggered_by_comment }}"
          else
            echo "Not triggered by workflow_call, no triggered_by_comment input"
          fi
