name: Build PullRequest

on:
  push:
  workflow_call:
    inputs:
      triggered_by_comment:
        type: boolean
        required: false

jobs:
  main:
    name: Create ota commit
    runs-on: ubuntu-latest
    steps:
      - name: Print triggered_by_comment
        run: |
            echo "triggered_by_comment: ${{ inputs.triggered_by_comment }}"
      - name: Print current branch
        run: |
            echo "Current branch: ${{ github.ref }}"
            echo "Branch name: ${{ github.ref_name }}"
  one:
    name: Create ota commit
    runs-on: macos-latest
    steps:
      - name: Print triggered_by_comment
        run: |
            echo "triggered_by_comment: ${{ inputs.triggered_by_comment }}"
  tow:
    name: Create ota commit
    runs-on: macos-latest
    steps:
      - name: Print triggered_by_comment
        run: |
            echo "triggered_by_comment: ${{ inputs.triggered_by_comment }}"

