name: /ota
on:
  issue_comment:
    types: [created]

jobs:
  main:
    name: Create ota commit
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/ota')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create ota
        uses: ./.github/workflows/build-pr.yml
        with:
          triggered_by_comment: true

  call-workflow:
    runs-on: ubuntu-latest
    needs: [main]
    steps:
      - name: Add reaction to comment
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context.payload)
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: "rocket",
            });
