name: /ota
on:
  issue_comment:
    types: [created]

name: /ota
on:
  issue_comment:
    types: [created]

jobs:
  add-initial-reaction-and-get-pr-info:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/ota')
    runs-on: ubuntu-latest
    outputs:
      pr_branch: ${{ steps.get-pr-info.outputs.head_ref }}
    steps:
      - name: Get PR info
        id: get-pr-info
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            core.setOutput('head_ref', pullRequest.head.ref);
            return pullRequest.head.ref;

      - name: Add rocket reaction to comment
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: "rocket",
            });

  build-ota:
    needs: [add-initial-reaction-and-get-pr-info]
    name: Create ota
    uses: ./.github/workflows/build-pr.yml
    with:
      triggered_by_comment: true
      branch_name: ${{ needs.add-initial-reaction-and-get-pr-info.outputs.pr_branch }}

  add-completion-reaction:
    needs: [build-ota]
    runs-on: ubuntu-latest
    steps:
      - name: Add completion reaction to comment
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: "hooray",
            });
