name: /ota
on:
  issue_comment:
    types: [created]

jobs:
  add-initial-reaction:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/ota')
    runs-on: ubuntu-latest
    steps:
      - name: Add initial reaction to comment
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: "rocket",
            });

  build-ota:
    needs: [add-initial-reaction]
    name: Create ota
    uses: ./.github/workflows/build-pr.yml
    with:
      triggered_by_comment: true

  add-completion-reaction:
    needs: [build-ota]
    runs-on: ubuntu-latest
    steps:
      - name: Add completion reaction to comment
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: "hooray",
            });
